### ISSUE TITLE
Integración

### ISSUE THREAD

**Issue by cristianjcdigital** [coreBOS/MauticStripeBundle#1]
Hola,

¿Sigue funcionando su repositorio para mautic? ¿Puede darme explicaciones de como integrarlo?

Saludos.
Cristian.

**Comment by joebordes** [comment]
Hola Cristian

Lo siento pero ya no estamos trabajando con esta extensión. El proyecto no salió y esta extensión ya no nos ha hecho falta.

**Comment by cristianjcdigital** [comment]
Gracias.
